server:
  port: 11004

spring:
  application:
    name: rocketmq-produce
  cloud:
    stream:
      bindings:
        test-out-0:
          destination: test-topic
          content-type: application/json
          group: produce-group
      rocketmq:
        binder:
          # RocketMQ 服务地址
          name-server: 192.168.28.130:9876

logging:
  level:
    org.springframework.context.support: debug